/**
 * The Sneaker Database
 * Sneaker Database API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@tg4.solutions
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SneakerMedia } from './sneakerMedia';


export interface Sneaker { 
    id: string;
    brand: string;
    colorway: string;
    gender: string;
    media: SneakerMedia;
    releaseDate: string;
    retailPrice: number;
    styleId: string;
    title: string;
    year: number;
}
