/**
 * The Sneaker Database
 * Sneaker Database API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@tg4.solutions
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SneakerMedia { 
    imageUrl?: string;
    smallImageUrl?: string;
    thumbUrl?: string;
}
